require("ammar.pluginconfigs.telescope")
require("ammar.pluginconfigs.colorscheme")
require("ammar.pluginconfigs.treesitter")
require("ammar.pluginconfigs.lsp")
require("ammar.pluginconfigs.tree")
require("ammar.pluginconfigs.lualine")
